---
language: node_js
node_js:
  - stable
before_install:
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo generate
deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
  bucket: "hexo-test-travis"
  skip_cleanup: true
  region: eu-west-1
  local_dir: public

  
